/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Views;

import Controls.CtlPatient;
import Models.StudentModel;
import java.awt.Frame;
import java.time.LocalDateTime;
import javax.swing.JFrame;
import javax.swing.SwingUtilities;

/**
 *
 * @author ITS
 */
public class AddStudentForm extends javax.swing.JDialog {
    
    private CtlPatient patient = new CtlPatient();

    /**
     * Creates new form VUpdatePatients 
     */
    public AddStudentForm(Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        setLocationRelativeTo(null);
        setResizable(false);
        pack();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        txtMajor = new com.raven.swing.MyTextField();
        lblAddress = new javax.swing.JLabel();
        txtAddress = new com.raven.swing.MyTextField();
        lblName = new javax.swing.JLabel();
        txtName = new com.raven.swing.MyTextField();
        lblAge = new javax.swing.JLabel();
        lblTitle = new javax.swing.JLabel();
        txtAge = new com.raven.swing.MyTextField();
        btnِAddPatient = new com.raven.swing.Button();
        lblGender = new javax.swing.JLabel();
        lblPhone = new javax.swing.JLabel();
        txtEmail = new com.raven.swing.MyTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLayeredPane1.setBackground(new java.awt.Color(255, 255, 255));
        jLayeredPane1.setOpaque(true);

        txtMajor.setBackground(new java.awt.Color(204, 204, 204));
        txtMajor.setForeground(new java.awt.Color(0, 0, 0));
        txtMajor.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        txtMajor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtMajorKeyTyped(evt);
            }
        });

        lblAddress.setFont(new java.awt.Font("Simplified Arabic", 1, 14)); // NOI18N
        lblAddress.setText("العنوان");

        txtAddress.setBackground(new java.awt.Color(204, 204, 204));
        txtAddress.setForeground(new java.awt.Color(0, 0, 0));
        txtAddress.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        txtAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAddressActionPerformed(evt);
            }
        });

        lblName.setFont(new java.awt.Font("Simplified Arabic", 1, 14)); // NOI18N
        lblName.setText("الاسم");

        txtName.setBackground(new java.awt.Color(204, 204, 204));
        txtName.setForeground(new java.awt.Color(0, 0, 0));
        txtName.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        txtName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameActionPerformed(evt);
            }
        });

        lblAge.setFont(new java.awt.Font("Simplified Arabic", 1, 14)); // NOI18N
        lblAge.setText("العمر");

        lblTitle.setFont(new java.awt.Font("Simplified Arabic", 1, 18)); // NOI18N
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("إضافة طالب");

        txtAge.setBackground(new java.awt.Color(204, 204, 204));
        txtAge.setForeground(new java.awt.Color(0, 0, 0));
        txtAge.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        txtAge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAgeActionPerformed(evt);
            }
        });
        txtAge.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtAgeKeyTyped(evt);
            }
        });

        btnِAddPatient.setBackground(new java.awt.Color(51, 51, 51));
        btnِAddPatient.setForeground(new java.awt.Color(255, 255, 255));
        btnِAddPatient.setText("إضافة");
        btnِAddPatient.setFont(new java.awt.Font("Simplified Arabic", 1, 14)); // NOI18N
        btnِAddPatient.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnِAddPatient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnِAddPatientActionPerformed(evt);
            }
        });

        lblGender.setFont(new java.awt.Font("Simplified Arabic", 1, 14)); // NOI18N
        lblGender.setText("البريد الالكتروني");

        lblPhone.setFont(new java.awt.Font("Simplified Arabic", 1, 14)); // NOI18N
        lblPhone.setText("التخصص");

        txtEmail.setBackground(new java.awt.Color(204, 204, 204));
        txtEmail.setForeground(new java.awt.Color(0, 0, 0));
        txtEmail.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        txtEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailActionPerformed(evt);
            }
        });
        txtEmail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtEmailKeyTyped(evt);
            }
        });

        jLayeredPane1.setLayer(txtMajor, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(lblAddress, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(txtAddress, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(lblName, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(txtName, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(lblAge, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(lblTitle, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(txtAge, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(btnِAddPatient, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(lblGender, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(lblPhone, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(txtEmail, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane1Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(txtName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(lblName))
                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                        .addGap(275, 275, 275)
                        .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane1Layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(btnِAddPatient, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtEmail, javax.swing.GroupLayout.DEFAULT_SIZE, 267, Short.MAX_VALUE)
                                    .addComponent(txtAddress, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblGender)
                                    .addComponent(lblAddress))
                                .addGap(16, 16, 16)
                                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtAge, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtMajor, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblPhone, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblAge, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane1Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(lblTitle)
                .addGap(50, 50, 50)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblName))
                .addGap(55, 55, 55)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAge)
                    .addComponent(txtAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblGender)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(78, 78, 78)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPhone)
                    .addComponent(txtMajor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAddress)
                    .addComponent(txtAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                .addComponent(btnِAddPatient, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtMajorKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMajorKeyTyped
        if (!Character.isDigit(evt.getKeyChar()) | txtMajor.getText().length() == 9) {
            evt.consume();
        }
    }//GEN-LAST:event_txtMajorKeyTyped

    private void txtAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAddressActionPerformed

    private void txtNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameActionPerformed

    private void txtAgeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAgeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAgeActionPerformed

    private void txtAgeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAgeKeyTyped
        if (!Character.isDigit(evt.getKeyChar()) | txtAge.getText().length() == 2) {
            evt.consume();
        }
    }//GEN-LAST:event_txtAgeKeyTyped

    private void btnِAddPatientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnِAddPatientActionPerformed
        VMessage message = new VMessage((java.awt.Frame) SwingUtilities.getWindowAncestor(this), true);
        if (!txtName.getText().trim().isEmpty() & txtName.getText().length() >= 3) {
            try {
                int age = Integer.parseInt(txtAge.getText());
                if (txtEmail.getText().trim().isEmpty()) {
                    if (txtMajor.getText().trim().isEmpty()) {
                        if (!txtAddress.getText().trim().isEmpty()) {
                            
                            StudentModel studentModel = new StudentModel();
                            studentModel.setFull_name(txtName.getText());
                            studentModel.setAge(age);
                            studentModel.setEmail(txtEmail.getText());
                            studentModel.setMajor(txtMajor.getText());
                            studentModel.setAddress(txtAddress.getText());
                            try {
//                                patient.insert(mPatient);
                                message.setLblTitle("تم الإضافة بنجاح");
                                message.setVisible(true);
                            } catch (Exception ex) {
                                ex.printStackTrace();
                            }
                            this.dispose();
                            
                        } else {
                            message.setLblTitle("يجب أن تدخل عنوان الطالب");
                            message.setVisible(true);
                            txtAddress.requestFocus();
                        }
                    } else {
                        message.setLblTitle("يجب أن تدخل تخصص الطالب");
                        message.setVisible(true);
                        txtMajor.requestFocus();
                    }
                } else {
                    message.setLblTitle("يجب أن تدخل البريد الإلتكتروني");
                }
            } catch (NumberFormatException ex) {
                message.setLblTitle("یجب أن تدخل عمر االطالب ");
                message.setVisible(true);
                txtAge.requestFocus();
            }
        } else {
            message.setLblTitle("يجب التأكد من الاسم");
            message.setVisible(true);
            txtName.requestFocus();
        }
    }//GEN-LAST:event_btnِAddPatientActionPerformed

    private void txtEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailActionPerformed

    private void txtEmailKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEmailKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        java.awt.EventQueue.invokeLater(() -> {
            AddStudentForm dialog = new AddStudentForm(new JFrame(), true);
            dialog.setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.raven.swing.Button btnِAddPatient;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JLabel lblAddress;
    private javax.swing.JLabel lblAge;
    private javax.swing.JLabel lblGender;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblPhone;
    private javax.swing.JLabel lblTitle;
    private com.raven.swing.MyTextField txtAddress;
    private com.raven.swing.MyTextField txtAge;
    private com.raven.swing.MyTextField txtEmail;
    private com.raven.swing.MyTextField txtMajor;
    private com.raven.swing.MyTextField txtName;
    // End of variables declaration//GEN-END:variables
}
